# Generated by Django 3.2.12 on 2022-04-13 07:22

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('company', models.CharField(max_length=400)),
                ('job_type', models.CharField(choices=[('Remote', 'Remote'), ('Internship', 'Internship'), ('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Internship, Part Time', 'Internship, Part Time'), ('Part Time, Full Time', 'Part Time, Full Time')], max_length=400)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=400, null=True)),
                ('degree', models.CharField(choices=[('Bachelor in CS', 'Bachelor in CS'), ('Bachelor Any', 'Bachelor Any'), ('Bachelor CS/IT/EC/ME', 'Bachelor CS/IT/EC/ME'), ('Master in CS', 'Master in CS'), ('MCA, Mtech', 'MCA, Mtech'), ('MCA, Mtech in CS', 'MCA, Mtech in CS'), ('BCA, BSC CS, Btech CS/IT', 'BCA, BSC CS, Btech CS/IT'), ('Btech CS/IT', 'Btech CS/IT'), ('Btech Any Branch', 'Btech Any Branch'), ('Any', 'Any')], max_length=400, null=True)),
                ('experience', models.CharField(blank=True, max_length=400, null=True)),
                ('description', tinymce.models.HTMLField(null=True)),
                ('responsibility', tinymce.models.HTMLField(null=True)),
                ('req_skills', tinymce.models.HTMLField(null=True)),
                ('additional', tinymce.models.HTMLField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
